name: data_science_project
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - imbalanced-learn
  - matplotlib
  - seaborn
  - plotly
  - streamlit
  - tqdm
  - joblib
  - shap
  - pip
  - pip:
    - kagglehub>=0.1.0
